### ISSUE TITLE
Suspected cheating

### ISSUE THREAD

**Issue by SleepyRiceYang** [WeijiaZhang24/CausalMIL#1]
In your `colon_cancer.py` script, within the `training_procedure` function, `train_bags = train_bags + test_bags`, it seems that you used the test set during the training process. Normally, the labels of the test set are considered unknown, as they are meant to evaluate the model's performance on unseen data. However, in your implementation, you appear to have leveraged the labels from the test set in the auxiliary loss computation. This raises the question: Is the model supposed to benefit from the label information of the test set, which is typically reserved for validation purposes only?

**Comment by SleepyRiceYang** [comment]
Apologies for the oversight. It's my mistake. I understand now that your task requires bag-level supervision to predict instance labels under the guidance of bag labels.

**Comment by WeijiaZhang24** [comment]
Hi Yang,

The goal is indeed predicting instance/patch labels from only bag supervision. However, if you comment out that line, and just train using training bag labels, it is still very straightforward to get instance-level AUCPR much better than attention-based MIL algorithms (with a smaller lr, e.g., 1e-4).

**Comment by SleepyRiceYang** [comment]
@WeijiaZhang24 Thank you for your patient and detailed response.
